#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: fbbd4e3
#
# Source0 file verified with key 0xD7574483BB57B18D (jr@jriddell.org)
#
Name     : plasma-activities-stats
Version  : 6.3.3
Release  : 20
URL      : https://download.kde.org/stable/plasma/6.3.3/plasma-activities-stats-6.3.3.tar.xz
Source0  : https://download.kde.org/stable/plasma/6.3.3/plasma-activities-stats-6.3.3.tar.xz
Source1  : https://download.kde.org/stable/plasma/6.3.3/plasma-activities-stats-6.3.3.tar.xz.sig
Source2  : D7574483BB57B18D.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: plasma-activities-stats-data = %{version}-%{release}
Requires: plasma-activities-stats-lib = %{version}-%{release}
Requires: plasma-activities-stats-license = %{version}-%{release}
BuildRequires : boost-dev
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : glibc-dev
BuildRequires : gnupg
BuildRequires : plasma-activities-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# KActivitiesStats
Library to access the usage statistics data collected by the KDE activity manager.

%package data
Summary: data components for the plasma-activities-stats package.
Group: Data

%description data
data components for the plasma-activities-stats package.


%package dev
Summary: dev components for the plasma-activities-stats package.
Group: Development
Requires: plasma-activities-stats-lib = %{version}-%{release}
Requires: plasma-activities-stats-data = %{version}-%{release}
Provides: plasma-activities-stats-devel = %{version}-%{release}
Requires: plasma-activities-stats = %{version}-%{release}

%description dev
dev components for the plasma-activities-stats package.


%package lib
Summary: lib components for the plasma-activities-stats package.
Group: Libraries
Requires: plasma-activities-stats-data = %{version}-%{release}
Requires: plasma-activities-stats-license = %{version}-%{release}

%description lib
lib components for the plasma-activities-stats package.


%package license
Summary: license components for the plasma-activities-stats package.
Group: Default

%description license
license components for the plasma-activities-stats package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) D7574483BB57B18D' gpg.status
%setup -q -n plasma-activities-stats-6.3.3
cd %{_builddir}/plasma-activities-stats-6.3.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1742508495
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1742508495
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/plasma-activities-stats
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/e712eadfab0d2357c0f50f599ef35ee0d87534cb || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/20079e8f79713dce80ab09774505773c926afa2a || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/3c3d7573e137d48253731c975ecf90d74cfa9efe || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/757b86330df80f81143d5916b3e92b4bcb1b1890 || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/plasma-activities-stats-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/plasma-activities-stats/e458941548e0864907e654fa2e192844ae90fc32 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/qlogging-categories6/plasma-activities-stats.categories
/usr/share/qlogging-categories6/plasma-activities-stats.renamecategories

%files dev
%defattr(-,root,root,-)
/usr/include/PlasmaActivitiesStats/PlasmaActivities/Stats/Cleaning
/usr/include/PlasmaActivitiesStats/PlasmaActivities/Stats/Query
/usr/include/PlasmaActivitiesStats/PlasmaActivities/Stats/ResultModel
/usr/include/PlasmaActivitiesStats/PlasmaActivities/Stats/ResultSet
/usr/include/PlasmaActivitiesStats/PlasmaActivities/Stats/ResultWatcher
/usr/include/PlasmaActivitiesStats/PlasmaActivities/Stats/Terms
/usr/include/PlasmaActivitiesStats/plasmaactivitiesstats/cleaning.h
/usr/include/PlasmaActivitiesStats/plasmaactivitiesstats/plasmaactivitiesstats_export.h
/usr/include/PlasmaActivitiesStats/plasmaactivitiesstats/query.h
/usr/include/PlasmaActivitiesStats/plasmaactivitiesstats/resultmodel.h
/usr/include/PlasmaActivitiesStats/plasmaactivitiesstats/resultset.h
/usr/include/PlasmaActivitiesStats/plasmaactivitiesstats/resultwatcher.h
/usr/include/PlasmaActivitiesStats/plasmaactivitiesstats/terms.h
/usr/include/PlasmaActivitiesStats/plasmaactivitiesstats_version.h
/usr/lib64/cmake/PlasmaActivitiesStats/PlasmaActivitiesStatsConfig.cmake
/usr/lib64/cmake/PlasmaActivitiesStats/PlasmaActivitiesStatsConfigVersion.cmake
/usr/lib64/cmake/PlasmaActivitiesStats/PlasmaActivitiesStatsLibraryTargets-relwithdebinfo.cmake
/usr/lib64/cmake/PlasmaActivitiesStats/PlasmaActivitiesStatsLibraryTargets.cmake
/usr/lib64/libPlasmaActivitiesStats.so
/usr/lib64/pkgconfig/PlasmaActivitiesStats.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libPlasmaActivitiesStats.so.1
/usr/lib64/libPlasmaActivitiesStats.so.6.3.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/plasma-activities-stats/20079e8f79713dce80ab09774505773c926afa2a
/usr/share/package-licenses/plasma-activities-stats/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/plasma-activities-stats/3c3d7573e137d48253731c975ecf90d74cfa9efe
/usr/share/package-licenses/plasma-activities-stats/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/plasma-activities-stats/757b86330df80f81143d5916b3e92b4bcb1b1890
/usr/share/package-licenses/plasma-activities-stats/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/plasma-activities-stats/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/plasma-activities-stats/e458941548e0864907e654fa2e192844ae90fc32
/usr/share/package-licenses/plasma-activities-stats/e712eadfab0d2357c0f50f599ef35ee0d87534cb
